// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UserCreation.Controllers {
    public partial class EmployeeController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EmployeeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddNew() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddNew);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Created() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Created);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SignOn() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SignOn);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EmployeeController Actions { get { return MVC.Employee; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Employee";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Add = "Add";
            public readonly string AddNew = "AddNew";
            public readonly string Created = "Created";
            public readonly string AllPending = "AllPending";
            public readonly string SignOn = "SignOn";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_EmployeeController: UserCreation.Controllers.EmployeeController {
        public T4MVC_EmployeeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Add() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Add);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddNew(UserCreation.ViewModels.NewEmployee newEmployee) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddNew);
            callInfo.RouteValueDictionary.Add("newEmployee", newEmployee);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Created(UserCreation.ViewModels.NewEmployee newEmployee) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Created);
            callInfo.RouteValueDictionary.Add("newEmployee", newEmployee);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AllPending() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AllPending);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SignOn(int newEmployeeId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SignOn);
            callInfo.RouteValueDictionary.Add("newEmployeeId", newEmployeeId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
