// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
using UserCreation.ViewModels;

namespace UserCreation.Controllers {
    public partial class PayrollController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PayrollController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PayrollController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.PartialViewResult BankInformation() {
            return new T4MVC_PartialViewResult(Area, Name, ActionNames.BankInformation);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PayrollController Actions { get { return MVC.Payroll; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Payroll";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string BankInformation = "BankInformation";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_PayrollController: UserCreation.Controllers.PayrollController {
        public T4MVC_PayrollController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.PartialViewResult BankInformation(int employeeId) {
            var callInfo = new T4MVC_PartialViewResult(Area, Name, ActionNames.BankInformation);
            callInfo.RouteValueDictionary.Add("employeeId", employeeId);
            return callInfo;
        }

        public override System.Web.Mvc.PartialViewResult BankInformation(EmployeePayrollInformationViewModel employeePayrollInformation) {
            var callInfo = new T4MVC_PartialViewResult(Area, Name, ActionNames.BankInformation);
            callInfo.RouteValueDictionary.Add("employeePayrollInformation", employeePayrollInformation);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
